// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace TA.PracticeService.CodeFirst.Maps
{
    using TA.PracticeService.CodeFirst.Entities;

    // Employees
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class EmployeeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Employee>
    {
        public EmployeeConfiguration()
            : this("dbo")
        {
        }

        public EmployeeConfiguration(string schema)
        {
            Property(x => x.Forename).IsOptional();
            Property(x => x.Surname).IsOptional();
            Property(x => x.JoiningDate).IsOptional();
            Property(x => x.EndDate).IsOptional();
            Property(x => x.MiddleName).IsOptional();
            Property(x => x.PayrollId).IsOptional();
            Property(x => x.CreatedDepartmentId).IsOptional();
            Property(x => x.UpdatedDepartmentId).IsOptional();

            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
