// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TA.PracticeService.CodeFirst.Entities
{
    using TA.PracticeService.CodeFirst.Maps;

    // Departments
    [Table("Departments", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class Department
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.Departments", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Column(@"Name", Order = 2, TypeName = "nvarchar(max)")]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name

        [Column(@"Description", Order = 3, TypeName = "nvarchar(max)")]
        [Display(Name = "Description")]
        public string Description { get; set; } // Description

        [Column(@"DepartmentCode", Order = 4, TypeName = "nvarchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Department code")]
        public string DepartmentCode { get; set; } // DepartmentCode (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child Employees where [Employees].[CreatedDepartmentId] point to this entity (FK_Employees_CreatedBy_User)
        /// </summary>
        public virtual System.Collections.Generic.IList<Employee> CreatedDepartment { get; set; } = new System.Collections.Generic.List<Employee>(); // Employees.FK_Employees_CreatedBy_User
        /// <summary>
        /// Child Employees where [Employees].[UpdatedDepartmentId] point to this entity (FK_Employees_UpdatedBy_User)
        /// </summary>
        public virtual System.Collections.Generic.IList<Employee> UpdatedDepartment { get; set; } = new System.Collections.Generic.List<Employee>(); // Employees.FK_Employees_UpdatedBy_User
    }

}
// </auto-generated>
